services:
  sillytavern:
    build: ./
    ports:
      - "8080:8000/tcp"
    volumes:
      # Data directories; should be owned by UID 10000
      - ./persist/plugins:/home/node/app/plugins:rw
      - ./persist/config:/home/node/app/config:rw
      - ./persist/data:/home/node/app/data:rw
